#      .
#     / V\
#   / `  /
#  <<   |    External Postgres example for mautrix-googlechat.
#  /    |    Disable bundled postgres and provide explicit connection fields.
#

postgres:
  enabled: false

database:
  postgres:
    host: postgres.example.com
    port: 5432
    user: mautrix_googlechat
    password:
      value: replace_me
      # Remove `value` and replace with the below to use an external secret
			# existingSecret: my-postgres-password
      # existingSecretKey: password
    database: mautrix_googlechat
    sslMode: require

homeserver:
  domain: matrix.example.com
