apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baibot.configSecretName" . }}
  labels:
    {{- include "baibot.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
{{ include "baibot.computedConfig" . | trim | nindent 4 }}
