{{- $support := include "baibot.persistenceSupportSecretData" . | fromYaml -}}
{{- if gt (len $support) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baibot.runtimeSupportSecretName" . }}
  labels:
    {{- include "baibot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if index $support "sessionManaged" }}
  sessionEncryptionKey: {{ index $support "sessionValue" | quote }}
  {{- end }}
  {{- if index $support "configManaged" }}
  configEncryptionKey: {{ index $support "configValue" | quote }}
  {{- end }}
{{- end }}
