{{- $passwordCfg := (get (.Values.database.postgres | default dict) "password") | default dict -}}
{{- if and .Values.postgres.enabled (eq ((get $passwordCfg "existingSecret") | default "") "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-googlechat.postgresFullname" . }}
  labels:
    {{- include "mautrix-googlechat.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
type: Opaque
stringData:
  password: {{ include "mautrix-googlechat.databasePostgresPassword" . | quote }}
{{- end }}
